version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djgo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    depends_on:
      - db

  db:
    image: mongo:5.0
    container_name: dj_mongo
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

volumes:
  mongo_data: