services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djgo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_HOST=db
      - MONGO_URI=mongodb://root:root@db:27017/
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mongo:5.0
    container_name: dj_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data: