version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - admin-network
    environment:
      - NODE_ENV=production

networks:
  admin-network: 