version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "8080:80"
    networks:
      - admin-network
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000

networks:
  admin-network: 